//{{NO_DEPENDENCIES}}
// Metrowerks Resource Editor generated include file.
// Used by interface.rc
//

#pragma once

// BITMAPS

// Definitions for the image quality bitmaps

#define IDB_BITMAP1                 	   	101
#define IDB_BITMAP2        	            	102
#define IDB_BITMAP3         	           	103

#define	IDR_SMALLBLANK						120
#define	IDR_LARGEBLANK						121

#define	ID_BAD_QUALITY_BITMAP				150
#define ID_GOOD_QUALITY_BITMAP				151
#define	ID_CAUTION_QUALITY_BITMAP			152

#define ID_BATTERY_OK_BITMAP				160
#define ID_BATTERY_WEAK_BITMAP				161
#define ID_BATTERY_EMPTY_BITMAP				162

#define ID_TOP_OF_HEAD_SIDEWAYS_BITMAP     	201
#define ID_TOP_OF_HEAD_NORMAL_BITMAP        202

// MENUITEMS

#define	ID_FILE_EXPORT_REPORTS				201
#define	ID_FILE_PROPERTIES					202
#define	ID_FILE_REPORTING_OPTIONS			203
#define	ID_FILE_INSTALL_LICENSE				204
#define	ID_FILE_DISPLAY_LICENSE				205
#define	ID_FILE_FLATTEN_REPORTS				206

// Accelerator Tables

#define	IDR_CAMFRAME_ACC					101
#define	IDR_DISKFRAME_ACC					102

// CONTROLS

// These are definitions for the objects in the main window

#define	IDC_MAIN_CAMERA						100
#define	IDC_MAIN_DISK						101
#define	IDC_MAIN_REPORTS					102
#define	IDC_MAIN_ABOUT						103
#define	IDC_MAIN_EXIT						104
#define IDC_MAIN_ADVANCED_FEATURES			105
#define IDC_MAIN_SESSION					106

// Accelerator table for the main window

#define	IDR_MAINWINDOW						100

// These are definitions for the objects in the disk window

#define	IDC_DISK_UP_PROGRESS_CAPTION		200
#define	IDC_DISK_SIDE_PROGRESS_CAPTION		201
#define	IDC_DISK_UP_PROGRESS_BAR			202
#define	IDC_DISK_SIDE_PROGRESS_BAR			203
#define	IDC_DISK_UP_VIEW					204
#define	IDC_DISK_SIDE_VIEW					205
#define	IDC_DISK_UP_QUALITY_ICON			206
#define	IDC_DISK_SIDE_QUALITY_ICON			207
#define	IDC_DISK_UP_CAPTION					208
#define	IDC_DISK_SIDE_CAPTION				209
#define	IDC_DISK_SELECT_UP_BUTTON			210
#define	IDC_DISK_SELECT_SIDE_BUTTON			211
#define	IDC_DISK_ANIMATE_CHECKBOX			212
#define	IDC_DISK_NAME_EDIT_FIELD_CAPTION	213
#define	IDC_DISK_NAME_EDIT_FIELD			214
#define	IDC_DISK_CANCEL						215
#define	IDC_DISK_OK							216
#define IDC_DISK_LICENSE_CAPTION			217
#define IDC_DISK_SESSION_CAPTION			218
#define	IDC_DISK_UP_ZOOM_BUTTON				219
#define	IDC_DISK_SIDE_ZOOM_BUTTON			220
#define	IDC_DISK_SIDE_TOP_OF_HEAD_BITMAP	221

// These are definitions for the objects in the camera window

#define IDC_CAMERA_UP_PROGRESS_CAPTION		300
#define IDC_CAMERA_SIDE_PROGRESS_CAPTION	301
#define IDC_CAMERA_UP_PROGRESS_BAR			302
#define IDC_CAMERA_SIDE_PROGRESS_BAR		303
#define IDC_CAMERA_UP_VIEW					304
#define IDC_CAMERA_SIDE_VIEW				305
#define IDC_CAMERA_UP_QUALITY_ICON			306
#define IDC_CAMERA_SIDE_QUALITY_ICON		307
#define IDC_CAMERA_UP_CAPTION				308
#define IDC_CAMERA_SIDE_CAPTION				309
#define IDC_CAMERA_SELECT_UP_BUTTON			310
#define IDC_CAMERA_SELECT_SIDE_BUTTON		311
#define IDC_CAMERA_ANIMATE_CHECKBOX			312
#define IDC_CAMERA_NAME_EDIT_FIELD_CAPTION	313
#define IDC_CAMERA_NAME_EDIT_FIELD			314
#define IDC_CAMERA_CANCEL					315
#define IDC_CAMERA_OK						316
#define IDC_CAMERA_LICENSE_CAPTION			317
#define IDC_CAMERA_SESSION_CAPTION			318
#define	IDC_CAMERA_UP_ZOOM_BUTTON			319
#define	IDC_CAMERA_SIDE_ZOOM_BUTTON			320
#define IDC_CAMERA_SIDE_TOP_OF_HEAD_BITMAP	321

// These are definitions for the objects in the Auto camera window

#define IDC_AUTO_CAMERA_UP_PROGRESS_CAPTION	350
#define IDC_AUTO_CAMERA_SIDE_PROGRESS_CAPTION	351
#define IDC_AUTO_CAMERA_UP_PROGRESS_BAR		352
#define IDC_AUTO_CAMERA_SIDE_PROGRESS_BAR	353
#define IDC_AUTO_CAMERA_UP_VIEW				354
#define IDC_AUTO_CAMERA_SIDE_VIEW			355
#define IDC_AUTO_CAMERA_UP_QUALITY_ICON		356
#define IDC_AUTO_CAMERA_SIDE_QUALITY_ICON	357
#define IDC_AUTO_CAMERA_UP_CAPTION			358
#define IDC_AUTO_CAMERA_SIDE_CAPTION		359
#define IDC_AUTO_CAMERA_NAME_CAPTION		360
#define IDC_AUTO_CAMERA_NAME_DISPLAY		361
#define IDC_AUTO_CAMERA_PROGRESS_CAPTION	362
#define IDC_AUTO_CAMERA_PROGRESS_BAR		363
#define IDC_AUTO_CAMERA_SESSION_CAPTION		364

// Camera Image Select Dialog and Controls

#define IDD_CAMERA_IMAGE_SELECT        		400
#define	IDC_CAMERA_PREVIEW					401
#define	IDC_CAMERA_IMAGE_NAME				402
#define	IDC_CAMERA_IMAGE_QUALITY			403
#define	IDC_CAMERA_LISTBOX					404

// File Open Preview Dialog Extension

#define IDD_FILEOPENPREVIEW            		500
#define IDC_IMAGE                     		501
#define IDC_QUALITY                   		502
#define IDC_PREVIEW                    		503


// These are definitions for the objects in the analysis window

#define IDC_ANALYSIS_PROGRESS_CAPTION		601
#define IDC_ANALYSIS_PROGRESS_BAR			602
#define IDC_ANALYSIS_UP_VIEW				603
#define IDC_ANALYSIS_SIDE_VIEW				604
#define IDC_ANALYSIS_UP_CAPTION				605
#define IDC_ANALYSIS_SIDE_CAPTION			606
#define IDC_ANALYSIS_MAIN_VIEW				607

// Copy Progress Dialog and Controls

#define	IDC_COPY_PROGRESS_ACTION			701
#define	IDC_COPY_PROGRESS_STEP				702
#define	IDC_COPY_PROGRESS_CANCEL			703

#define	IDD_SPLASH_DIALOG					900
#define IDC_SPLASH_VIEW						901

#define	IDR_SILENCE_WAVE					129		// Used for terminating the user's Startup Sound

// About Box and Controls

#define	IDD_ABOUT_DIALOG					1000
#define IDC_ABOUT_VERSION					1001
#define	IDC_ABOUT_PATENT					1002
#define	IDC_ABOUT_ADDRESS					1003
#define	IDC_ABOUT_PHONE						1004
#define	IDC_ABOUT_EMAIL						1005
#define	IDC_ABOUT_EMAIL_LINK				1006
#define	IDC_ABOUT_WWW						1007
#define	IDC_ABOUT_WWW_LINK					1008
#define	IDC_ABOUT_ACK						1009
#define	IDC_ABOUT_CREDITS					1010

// Properties Window and Controls

#define	IDD_PROPERTIES_DIALOG				1100

#define IDD_GENERALPROPS_PAGE				1150
#define	IDC_SAVEIMAGES						1151
#define	IDC_DISPLAYREPORT					1152
#define	IDC_DISPLAYSUMMARY					1153
#define	IDC_DONTDISPLAY						1154
#define	IDC_CAMERARATE						1155
#define	IDC_ADJREPORT						1156
#define	IDC_AFTERANALYSIS					1157
#define	IDC_REPORTFORMAT					1158
#define	IDC_REPORTLAYOUTBUTTON				1159
#define	IDC_USESESSIONS						1160
#define	IDC_REPORTINGOPTIONSGB				1161
#define	IDC_RUNOPTIONSGB					1162
#define IDC_GENPREFSAFTERLABEL				1163
#define	IDC_GENPREFSFORMATLABEL				1164
#define	IDC_AUTOSTART						1165
	
// Variables Page and Controls

#define	IDD_VARIABLES_PAGE					1200
#define	IDC_LAYOUTVARIABLELIST				1201
#define	IDC_LAYOUTNEWBUTTON					1202
#define	IDC_LAYOUTEDITBUTTON				1203
#define	IDC_LAYOUTDELETEBUTTON				1204
#define	IDC_LAYOUTSEPARATEDIALOG			1205

// Report Layout Page and Controls

#define IDD_REPORTLAYOUT_PAGE				1250
#define	IDC_LAYOUTCUSTOMTEXTTYPE			1251
#define	IDC_LAYOUTTEXTHTMLFORMAT			1252
#define	IDC_LAYOUTCUSTOMTEXTEDIT			1253
#define	IDC_LAYOUTREVERTTOSAVED				1254
#define	IDC_LAYOUTSETTODEFAULT				1255
#define	IDC_LAYOUTINSERTVARIABLE			1256
#define	IDC_LAYOUTDEFINETEXTLABEL			1257
#define	IDC_LAYOUTINSERTLABEL				1258

// Define Export Order Page and Controls

#define	IDD_DEFINEEXPORTORDER_PAGE			1300
#define	IDC_DEFINEEXPORTORDER_VARIABLELIST	1301
#define	IDC_DEFINEEXPORTORDER_MOVEUPBUTTON	1302
#define	IDC_DEFINEEXPORTORDER_MOVEDOWNBUTTON	1303
#define	IDC_DEFINEEXPORTORDER_REMOVEBUTTON	1304
#define	IDC_DEFINEEXPORTORDER_VARIABLEMENU	1305
#define IDC_DEFINEEXPORTORDERGB				1306
#define	IDC_DEFINEEXPORTORDERINSERTLABEL	1307

// Edit Variable Dialog and controls

#define	IDD_EDITVAR_DIALOG					1400
#define IDC_EDITVAR_VAR_NAMEFIELD			1401
#define	IDC_EDITVAR_VAR_TYPECAPTION			1402
#define IDC_EDITVAR_COMMENTFIELD			1403
#define	IDC_EDITVAR_FIXEDVALUEFIELD			1404
#define	IDC_EDITVAR_WHENTOPROMPTMENU		1405
#define	IDC_EDITVAR_PROMPTSTRINGFIELD		1406
#define	IDC_EDITVAR_VARTYPEMENU				1407
#define	IDC_EDITVAR_DEFINECHOICESBUTTON		1408
#define	IDC_EDITVAR_DEFAULTVALUEFIELD		1409
#define	IDC_EDITVAR_DEFAULTVALUECAPTION		1410
#define	IDC_EDITVAR_MUSTENTERCHECKBOX		1411
#define	IDC_EDITVAR_ENTRYFIELDLINESMENU		1412
#define	IDC_EDITVAR_CHECKEDCHECKBOX			1413
#define	IDC_EDITVAR_UNCHECKEDCHECKBOX		1414
#define	IDC_EDITVAR_DEFAULTMENUITEMMENU		1415
#define	IDC_EDITVAR_PROMPTFORVALUEBUTTON	1416
#define	IDC_EDITVAR_USEFIXEDVALUEBUTTON		1417
#define	IDC_EDITVAR_HIDECHECKBOX			1418
#define IDC_EDITVAR_LINESINENTRYCAPTION		1419

// Define Choices Dialog

#define	IDD_DEFINECHOICES_DIALOG			1500
#define	IDC_DEFINECHOICES_CHOICELIST		1501
#define	IDC_DEFINECHOICES_MOVEUPBUTTON		1502
#define	IDC_DEFINECHOICES_MOVEDOWNBUTTON	1503
#define	IDC_DEFINECHOICES_REMOVEBUTTON		1504
#define	IDC_DEFINECHOICES_NEWBUTTON			1505
#define	IDC_DEFINECHOICES_MODIFYBUTTON		1506
#define	IDC_DEFINECHOICES_VALUEFIELD		1507

// License Status Window and Controls

#define	IDD_LICENSE_STATUS_DIALOG			2000
#define	IDC_LICENSE_STATUS_EXPDATE			2001
#define	IDC_LICENSE_STATUS_ANALYSISRUNS		2002
#define	IDC_LICENSE_STATUS_CAPTION			2003

// License Expired Window and Controls

#define	IDD_LICENSE_EXPIRED_DIALOG			2100
#define	IDC_LICENSE_EXPIRED_CAPTION			2101

// License Entry Window and Controls

#define	IDD_LICENSE_ENTRY_DIALOG			2200
#define	IDC_LICENSE_ENTRY_PROMPT			2201
#define	IDC_LICENSE_ENTRY_CANCEL_BUTTON		2202
#define	IDC_LICENSE_ENTRY_FIELD1			2203
#define	IDC_LICENSE_ENTRY_FIELD2			2204
#define	IDC_LICENSE_ENTRY_FIELD3			2205
#define	IDC_LICENSE_ENTRY_FIELD4			2206
#define	IDC_LICENSE_ENTRY_CUSTID_FIELD		2207
#define	IDC_LICENSE_ENTRY_BOGUS_FIELD		2208

// Analysis Results Window and Controls

#define	IDD_SUMMARY_DIALOG					3000
#define	IDC_SUMMARY_NOTE_CAPTION			3001
#define	IDC_SUMMARY_NAME_CAPTION			3002
#define	IDC_SUMMARY_UP_CAPTION				3003
#define	IDC_SUMMARY_SIDE_CAPTION			3004
#define	IDC_SUMMARY_UP_TOP_RESULTS			3005
#define	IDC_SUMMARY_SIDE_TOP_RESULTS		3006
#define	IDC_SUMMARY_BOTTOM_CAPTION_1		3007
#define	IDC_SUMMARY_BOTTOM_CAPTION_2		3008
#define	IDC_SUMMARY_RETAKE_UP				3009
#define	IDC_SUMMARY_STARTOVER				3010
#define	IDC_SUMMARY_RETAKE_SIDE				3011
#define	IDC_SUMMARY_UP_VIEW					3012
#define	IDC_SUMMARY_SIDE_VIEW				3013
#define	IDC_SUMMARY_EYE0_VIEW				3014
#define	IDC_SUMMARY_EYE1_VIEW				3015
#define	IDC_SUMMARY_EYE2_VIEW				3016
#define	IDC_SUMMARY_EYE3_VIEW				3017
#define	IDC_SUMMARY_EYE4_VIEW				3018
#define	IDC_SUMMARY_EYE5_VIEW				3019
#define	IDC_SUMMARY_EYE6_VIEW				3020
#define	IDC_SUMMARY_EYE7_VIEW				3021
#define	IDC_SUMMARY_REPORT					3022
#define	IDC_SUMMARY_UP_ZOOM_BUTTON			3023
#define	IDC_SUMMARY_SIDE_ZOOM_BUTTON		3024

// Prepare Camera Dialog

#define	IDD_PREPARE_CAMERA_DIALOG			4000
#define	IDC_PREPARE_CAMERA_MANUAL_BUTTON	4001
#define	IDC_PREPARE_CAMERA_BITMAP			4002
#define	IDC_PREPARE_CAMERA_MANUAL_CAPTION	4003
#define	IDC_PREPARE_CAMERA_AUTO_CAPTION		4004

// Enter Name Dialog

#define	IDD_ENTER_NAME_DIALOG				4100
#define	IDC_ENTER_NAME_EDIT_FIELD			4101
#define	IDC_ENTER_NAME_LICENSE_CAPTION		4102
#define	IDC_ENTER_NAME_LENGTH_CAPTION		4103
#define	IDC_ENTER_NAME_SESSION_CAPTION		4104
#define	IDC_ENTER_NAME_SESSION_BUTTON		4105

// Prepare to Take Picture Dialog

#define	IDD_PREPARE_PICTURE_DIALOG			4200
#define	IDD_PREPARE_PICTURE_CAPTION			4201
#define	IDD_PREPARE_PICTURE_BITMAP			4202
#define	IDD_PREPARE_PICTURE_BATTERY_BITMAP	4203
#define	IDD_PREPARE_PICTURE_BATTERY_CAPTION	4204

// Verify Picture Dialog

#define	IDD_VERIFY_PICTURE_DIALOG			4300
#define	IDD_VERIFY_PICTURE_RETAKE_BUTTON	4301
#define	IDD_VERIFY_PICTURE_FILENAME_CAPTION	4302
#define	IDD_VERIFY_PICTURE_VIEW				4303
#define	IDD_VERIFY_PICTURE_CAPTION			4304
#define	IDD_VERIFY_PICTURE_QUALITY_CAPTION	4305
#define	IDD_VERIFY_PICTURE_TOP_BITMAP		4306
#define	IDD_VERIFY_PICTURE_SIDE_BITMAP		4307
#define	IDD_VERIFY_PICTURE_ZOOM_BUTTON		4308

// Erase Picture Dialog

#define	IDD_ERASE_PICTURE_DIALOG			4400

// Another Subject Dialog

#define	IDD_ANOTHER_SUBJECT_DIALOG			4500
#define	IDC_ANOTHER_SUBJECT_SESSION_CAPTION	4501
#define	IDC_ANOTHER_SUBJECT_SESSION_BUTTON	4502

// Another Session Dialog

#define	IDD_SHUTDOWN_SESSION_DIALOG			5000
#define	IDC_SHUTDOWN_SESSION_CAPTION		5001

// Startup Session Dialog

#define	IDD_STARTUP_SESSION_DIALOG			5100
#define	IDC_STARTUP_SESSION_CAPTION			5101

// Session Name Dialog

#define	IDD_SESSION_NAME_DIALOG				5200
#define	IDC_SESSION_NAME_SESSION_CAPTION	5201
#define	IDC_SESSION_NAME_SESSION_BUTTON		5202
#define	IDC_SESSION_NAME_EDIT_FIELD			5203
#define	IDC_SESSION_NAME_LENGTH_CAPTION		5204

// The Summary Zoom Dialog

#define	IDD_SUMMARY_ZOOM_DIALOG				5300
#define	IDC_SUMMARY_ZOOM_NAME_CAPTION		5301
#define	IDC_SUMMARY_ZOOM_MAIN_VIEW			5302
#define	IDC_SUMMARY_ZOOM_LEFT_EYE_VIEW		5303
#define	IDC_SUMMARY_ZOOM_RIGHT_EYE_VIEW		5304

// The Verify Zoom Dialog

#define	IDD_VERIFY_ZOOM_DIALOG				5400
#define	IDC_VERIFY_ZOOM_NAME_CAPTION		5401
#define	IDC_VERIFY_ZOOM_MAIN_VIEW			5402
#define	IDC_VERIFY_ZOOM_DOWNLOAD_BUTTON		5403
#define IDC_VERIFY_ZOOM_PROGRESS_BAR		5404

// Prompt for Variable Dialog

#define	IDD_PROMPT_FOR_VARIABLE_DIALOG		12000
#define	IDD_PROMPT_FOR_VARIABLE_GOBACK		12001

// Password Dialog

#define	IDD_PASSWORD_DIALOG					13000
#define	IDC_PASSWORD_FIELD					13001

// Accelerator Table for the Take Picture Dialog

#define	IDR_TAKEPICTUREDLG					1000
#define IDC_TAKE_PICTURE					1001

// This is the base resource ID for the Default Text Blocks for Reports

#define	IDS_DEFAULTTEXTBASE					10000

#define	IDS_DEFAULTVARBASE					32000

#define IDC_DEFAULT_VARIABLE_TABLE			1000
#define	IDC_DEFAULT_VARIABLE_TABLE_TYPE		1000